<?php echo $this->doctype() ?>
<html>
    <head>
       <?php 
           echo $this->headMeta() . PHP_EOL;
           echo $this->headTitle() . PHP_EOL;
           echo $this->headLink() . PHP_EOL;
           echo $this->headStyle() . PHP_EOL;
           echo $this->headScript() . PHP_EOL;
           echo $this->JQuery() . PHP_EOL;
       ?>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>